DROP DATABASE IF EXISTS AKAR;
CREATE DATABASE AKAR;
USE AKAR;
CREATE TABLE USUARIO(
IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT, NOMBRE VARCHAR(50), 
 APELLIDOP VARCHAR(50), APELLIDOM VARCHAR(50), CORREO VARCHAR(100), CONTRASENA VARCHAR(50),
 NOMUSUARIO VARCHAR(50), FECHA DATE, VER BOOLEAN);

CREATE TABLE REPORTE(
IDREPORTE INT PRIMARY KEY AUTO_INCREMENT, PROBLEMA VARCHAR(1024),
ESTATUS VARCHAR(40), SOLUCION VARCHAR(1024), FECHAI DATETIME, FECHAF DATETIME);

CREATE TABLE REPORTECAMBIOS(
IDREPORTECAMBIOS INT PRIMARY KEY AUTO_INCREMENT,
IDUSUARIO INT, IDREPORTE INT, FECHACAMBIO DATETIME,
ESTATUSI VARCHAR(40), ESTATUSF VARCHAR(40), 
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDREPORTE) REFERENCES REPORTE(IDREPORTE));

CREATE TABLE RELREPORTEENCARGADO(
IDRELREPORTEENCARGADO INT PRIMARY KEY AUTO_INCREMENT,
IDENCARGADO INT, IDREPORTE INT,
FOREIGN KEY (IDENCARGADO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDREPORTE) REFERENCES REPORTE(IDREPORTE));

CREATE TABLE RELREPORTEUSUARIO(
IDRELREPORTEUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
IDUSUARIO INT, IDREPORTE INT, 
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDREPORTE) REFERENCES REPORTE(IDREPORTE));	

CREATE TABLE TIPOUSUARIO(
IDTIPO INT PRIMARY KEY AUTO_INCREMENT,
TIPO VARCHAR(40));

CREATE TABLE RELTIPOUSUARIO(
IDRELTIPOUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
IDUSUARIO INT, IDTIPO INT,
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDTIPO) REFERENCES TIPOUSUARIO(IDTIPO)
);

CREATE TABLE JUEGO(
IDJUEGO INT PRIMARY KEY AUTO_INCREMENT,
NOMBREJUEGO VARCHAR(40));

CREATE TABLE RELJUEGOUSUARIO(
IDRELJUEGOUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
IDJUEGO INT,IDUSUARIO INT,PUNTAJE INT,
FOREIGN KEY (IDJUEGO) REFERENCES JUEGO(IDJUEGO),
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO));

CREATE TABLE MSJFORO(
IDMENSAJE INT PRIMARY KEY AUTO_INCREMENT,
IDAUTOR INT,
MENSAJE  VARCHAR(300),
HORA DATETIME,
FOREIGN KEY(IDAUTOR) REFERENCES USUARIO(IDUSUARIO) );

CREATE TABLE CHAT(
IDCHAT INT PRIMARY KEY AUTO_INCREMENT,
IDUSUARIO1 INT, IDUSUARIO2 INT,
FOREIGN KEY (IDUSUARIO1) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDUSUARIO2) REFERENCES USUARIO(IDUSUARIO));


CREATE TABLE RELCHATMENSAJE(
IDRELCHATMENSAJE INT PRIMARY KEY AUTO_INCREMENT,
IDCHAT INT, IDMENSAJE INT,
FOREIGN KEY(IDCHAT) REFERENCES CHAT(IDCHAT),
FOREIGN KEY(IDMENSAJE) REFERENCES MSJFORO(IDMENSAJE));

CREATE TABLE RELTUTORUCSA(
IDRELTUTORUCSA INT PRIMARY KEY AUTO_INCREMENT,
IDUSUARIO1 INT, IDUSUARIO2 INT,
FOREIGN KEY (IDUSUARIO1) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (IDUSUARIO2) REFERENCES USUARIO(IDUSUARIO));

CREATE TABLE RESPASS(
	IDTOKEN INT PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(43) NOT NULL,
    EXP TIMESTAMP NOT NULL
);

CREATE TABLE RELUSUARIORESPASS(
	IDRELUSRESS INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    IDRESPASS INT,
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    FOREIGN KEY(IDRESPASS) REFERENCES RESPASS(IDTOKEN)
);

INSERT INTO TIPOUSUARIO (TIPO) VALUES ('Psicólogo'), ('UCSA'),('Tutor'),('Externo'),
('Asistente'),('Gerente de Soporte'),('Ingeniero de Soporte'),('Gerente de Mantenimiento'),('Ingeniero de Mantenimiento'), ('Administrador');


ALTER TABLE MSJFORO CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE USUARIO CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;



